### ISSUE TITLE
Not available in composer

### ISSUE THREAD

**Issue by stanbellcom** [gaarf/XML-string-to-PHP-array#16]
This package is not longer available in composer. 
Has something happened?

**Comment by roland-d** [comment]
@stanbellcom Today I found out the same thing. This is what I have done for now:
1. Download the release package
2. Unpack it into folder `gaarf\xml-to-php-array\` inside the vendor folder
3. Add the following into my composer.json file or update the PSR-4 autoload if you already have it
```
"autoload": {
    "psr-4": {
      "Gaarf\\": "\\vendor\\gaarf\\xml-to-php-array\\src\\"
    }
  }
```
4. Run `composer dump-autoloader`
5. The class is now available

Hope this helps someone :)

**Comment by loekvangool** [comment]
It's `composer dump-autoload`

**Comment by roland-d** [comment]
@loekvangool Asbolutely, thank you. I updated the instructions.

**Comment by janbarasek** [comment]
@gaarf Can you release a new tag for Composer? Here: https://github.com/gaarf/XML-string-to-PHP-array/releases

Because this package is currently 17 commits behind since the last release.

![Snímek obrazovky 2020-10-25 v 19 12 58](https://user-images.githubusercontent.com/4738758/97115269-272da200-16f6-11eb-81f2-720f5257ae0d.png)

Thanks.

**Comment by janbarasek** [comment]
@roland-d Your solution is not suitable because it violates the principle of releasing packages. The right solution is to wait until the next stable version of the package comes out, or ask @gaarf.

**Comment by gaarf** [comment]
@janbarasek done! https://github.com/gaarf/XML-string-to-PHP-array/releases/tag/v1.1
